package in.codetripper.communik.notification;

public enum Status {
    NOTIFICATION_NEW, NOTIFICATION_STORED, NOTIFICATION_SENT, NOTIFICATION_SUCCESS, NOTIFICATION_FAILED, NOTIFICATION_RETRY_FAILED, NOTIFICATION_INPROGRESS
}
